#!/bin/sh
#
# Script to unload 8852au before suspend or hibernate, and restore on resume
# Save in /usr/lib/systemd/system-sleep/
#
case $1 in
  pre)
  # Shutdown
    modprobe -rv 8852au
    ;;
  post)
  # Resume
    modprobe -v 8852au
    ;;
esac
